apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-healthcare-deployment
  labels:
    app: ai-healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-healthcare
  template:
    metadata:
      labels:
        app: ai-healthcare
    spec:
      containers:
      - name: ai-healthcare
        image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/piyushrepo/ai-healthcare:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-secret
              key: gemini_api_key
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/app/firebase_key.json"
        volumeMounts:
        - name: firebase-key-volume
          mountPath: "/app/firebase_key.json"
          subPath: firebase_key.json

      volumes:
      - name: firebase-key-volume
        secret:
          secretName: firebase-key-secret
