apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-health-assistant-deployment
  namespace: "2401031"
  labels:
    app: ai-health-assistant

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-health-assistant

  template:
    metadata:
      labels:
        app: ai-health-assistant

    spec:
      imagePullSecrets:
        - name: nexus-secret

      containers:
        - name: ai-health-assistant
          image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/2401031/ai-health-assistant:v1
          ports:
            - containerPort: 8501

          # ==========================
          # ðŸ”¥ Environment Variables
          # ==========================
          env:
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gemini-secret
                  key: GEMINI_API_KEY

            - name: FIREBASE_KEY_PATH
              value: "/app/firebase_key.json"

          # ==========================
          # ðŸ”¥ Mount Firebase Secret
          # ==========================
          volumeMounts:
            - name: firebase-secret
              mountPath: /app/firebase_key.json
              subPath: firebase_key.json

      # ==========================
      # ðŸ”¥ Declare Volumes
      # ==========================
      volumes:
        - name: firebase-secret
          secret:
            secretName: firebase-secret
