apiVersion: v1
kind: Service
metadata:
  name: ai-health-assistant-service
  namespace: "2401031"
  labels:
    app: ai-health-assistant
spec:
  type: NodePort
  selector:
    app: ai-health-assistant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
