apiVersion: v1
kind: Service
metadata:
  name: ai-health-assistant-service
  labels:
    app: ai-health-assistant
spec:
  type: NodePort              # Use NodePort only if your college allows external access
  selector:
    app: ai-health-assistant  # Must match deployment labels
  ports:
    - port: 80                # Service Port (browser will use this)
      targetPort: 8501        # Streamlit container port
      nodePort: 30051         # NodePort (only for NodePort type)
